### ISSUE TITLE
I get error do the following:

### ISSUE THREAD

**Issue by lgaticaq** [franciscod/pyfprint-cffi#1]
I'm using the fingerprint reader Digitalpersona U.are.U 4500

```
import pyfprint
pyfprint.fp_init()
devs = pyfprint.discover_devices()
dev = devs[0]
dev.open()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/site-packages/pyfprint/pyfprint.py", line 80, in open
    raise "device open failed"
TypeError: exceptions must derive from BaseException
```

**Comment by franciscod** [comment]
You need permissions for the usb device. Try as root!

Another solution is to modify the device permissions, you can automate this
with udev rules (or similar mechanism).

**Comment by lgaticaq** [comment]
Thanks, I've resolvido following this guide http://fcns.eu/2012/04/29/fingerprint-reader/

**Comment by franciscod** [comment]
Awesome!

Doing chmod manually will work, but beware that if the device is
disconnected or the computer restarts the permissions will reset.

You can craft an udev rule so the permissions get set at boot :)
