### ISSUE TITLE
It is possible to lower the sensitivity to find the match?

### ISSUE THREAD

**Issue by lgaticaq** [franciscod/pyfprint-cffi#3]
It happened to me when I want to verify the fingerprint move slightly to place the finger and not found match.

**Comment by franciscod** [comment]
Have a look: https://github.com/franciscod/pyfprint-cffi/blob/master/pyfprint/pyfprint.py#L596

Tweaking the `THRESHOLD` might do the trick. Note that as `fp_img_compare_print_data_to_gallery` isn't `API EXPORTED` on libfprint, you must patch it (just add `API EXPORTED` before the function return type) and recompile it.

**Comment by franciscod** [comment]
Any update on this, @leonciokof?

**Comment by lgaticaq** [comment]
I think the solution is for enrolling more than once footprint, ideally about 5 versions.

**Comment by franciscod** [comment]
closing this by now
