### ISSUE TITLE
Error in raspberry pi

### ISSUE THREAD

**Issue by lgaticaq** [franciscod/pyfprint-cffi#4]
The error is triggered in https://github.com/franciscod/pyfprint-cffi/blob/master/pyfprint/pyfprint.py#L194 because r is equal to -22. 
You know who is that?

**Comment by franciscod** [comment]
In fp_enroll_finger_img, a negative value means an error ocurred. Let's have a look at libfprint's code!

https://github.com/anarsoul/libfprint/search?utf8=%E2%9C%93&q=fp_enroll_finger_img&type=Code

https://github.com/anarsoul/libfprint/blob/899c0a65a2edc7c799d6f2ed659ac0ccd36fce14/libfprint/sync.c#L176

You can see several `return -EINVAL;` there. EINVAL is that 22 you got, it's defined as Invalid argument ([reference](http://www-numi.fnal.gov/offline_software/srt_public_context/WebDocs/Errors/unix_system_errors.html))

I think building libfprint with debugging enabled is a good first step for troubleshooting the error. 

Which fingerprint reader device do you have? The Pi has some power issues on USB, you could try using a powered USB hub instead. Also, you can test on another computer with a good 500mA USB port.

**Comment by franciscod** [comment]
Any update on this, @leonciokof?

**Comment by lgaticaq** [comment]
I did not know how to do what you provided me. So we opted to change the raspberry for INTEL NUC. Currently I have libfprint installed from the repositories. How would need to do to compile with debug?

**Comment by franciscod** [comment]
I'm not sure about that: to begin with it try to compile `libfprint` from source. Given the vagueness of the issue I'm closing it, but please reopen it and comment further experience :)
