### ISSUE TITLE
memory leaks

### ISSUE THREAD

**Issue by umlaeute** [franciscod/pyfprint-cffi#9]
the wrapper has a number of memleaks: most of the objects allocated by libfprint are never released.

e.g. doing:

```
   import pyfprint as FP
   FP.fp_init()
   device=FP.discover_devices()[0]
   device.open()
   f0,_=device.enroll_finger()
   raw=bytes(f0.data())
   while True:
       f=FP.Fprint(raw)
   device.close()
   FP.fp_exit()
```

**Comment by umlaeute** [comment]
i see that there is a disabled (commented out) `__del__` method in the `Fprint` class.
i guess that this is for a reason. which one?

if it is for ref-counting the low-level data, i guess the proper way would be to wrap it into a lightway object that propery does the deallocation.

**Comment by franciscod** [comment]
I don't remember why the `__del__` method was commented out. Maybe because I didn't know how to port it from swig to cffi, or got lazy (probably the latter)

**Comment by umlaeute** [comment]
actually it was already ported.
the only thing i found was that it would free the `data_ptr` unconditionally (even if it was passed at object creation, so technically doesn't _belong_ to the object...)

**Comment by franciscod** [comment]
awesome! :D
